### ISSUE TITLE
Introduce a  #show command

### ISSUE THREAD

**Issue by angary** [vale1410/bule#28]
Currently there is just a `#hide` command which stops search variables front being show in stdout when solving / grounding. 

It would be helpful to have a `#show` command where only variables with `#show` in front of them are shown.

**Comment by AbdallahS** [comment]
You can now write `#hide` or `#show` directives. What happens for literals unspecified with such a directive is determined by the command-line option `--default_show` (check `bule2 --help`).

By the way, the commit prior to the one fixing this issue has changed the syntax a little bit
* "now grounding fact declarations need `#ground`, similar to `#exists` and `#forall`.
* the conjunctive grounding prefix is written `a[X], b[X] ::` instead of `:: a[X], b[X] ::`, and the disjunctive one is written `a[X], b[X] :` instead of `: a[X], b[X] :`.
* you can declaire multiple search variables, and multiple ground facts at once by separating with commas. E.g., `a[X] :: #exists[0] v(X), w(X).`.
